import type { ExternalArenaDto } from "./arena.contracts";

export const arenaMockDtos: ExternalArenaDto[] = [
  {
    tournament_slug: "devtest3",
    spectators_count: 124,
    server_time: "2026-06-04T18:10:00.000Z",
    leaderboard: [
      {
        trader_id: "trader_karlos",
        display_name: "Karlos Guzman",
        clan_name: "Bullfy Clan",
        avatar_url: "/avatars/karlos.svg",
        rank: 1,
        previous_rank: 1,
        score_pct: -0.91,
        pnl_amount: -91.32,
        balance_amount: 9908.68,
        trades_count: 34,
        win_rate_pct: 58,
      },
      {
        trader_id: "trader_tradermax",
        display_name: "TraderMax",
        clan_name: "Alpha Clan",
        avatar_url: "/avatars/tradermax.svg",
        rank: 2,
        previous_rank: 4,
        score_pct: -0.35,
        pnl_amount: -35.12,
        balance_amount: 9964.88,
        trades_count: 28,
        win_rate_pct: 61,
      },
      {
        trader_id: "trader_luna",
        display_name: "Luna Trader",
        clan_name: "Moon Clan",
        avatar_url: "/avatars/luna.svg",
        rank: 3,
        previous_rank: 2,
        score_pct: -1.24,
        pnl_amount: -124.31,
        balance_amount: 9875.69,
        trades_count: 41,
        win_rate_pct: 47,
      },
      {
        trader_id: "trader_fx",
        display_name: "FX Immortal",
        clan_name: "Legend Clan",
        avatar_url: "/avatars/fx.svg",
        rank: 4,
        previous_rank: 4,
        score_pct: -1.45,
        pnl_amount: -145.32,
        balance_amount: 9854.68,
        trades_count: 36,
        win_rate_pct: 52,
      },
      {
        trader_id: "trader_pipmaster",
        display_name: "PipMaster",
        clan_name: "Alpha Clan",
        avatar_url: "/avatars/pipmaster.svg",
        rank: 5,
        previous_rank: 6,
        score_pct: -1.78,
        pnl_amount: -178.04,
        balance_amount: 9821.96,
        trades_count: 29,
        win_rate_pct: 55,
      },
    ],
    metrics: [
      { label: "Volumen total", value: "$482K", trend: "UP" },
      { label: "Trades activos", value: "38", trend: "FLAT" },
      { label: "Mejor win rate", value: "61%", trend: "UP" },
      { label: "Drawdown medio", value: "1.2%", trend: "DOWN" },
    ],
    recent_activity: [
      {
        event_id: "evt_1",
        trader_name: "Luna Trader",
        description: "abrió una operación",
        asset_symbol: "GBPUSD",
        pnl_pct: 0,
        created_at: "2026-06-04T18:09:00.000Z",
      },
      {
        event_id: "evt_2",
        trader_name: "Karlos Guzman",
        description: "cerró una operación",
        asset_symbol: "EURUSD",
        pnl_pct: -0.42,
        created_at: "2026-06-04T18:08:00.000Z",
      },
      {
        event_id: "evt_3",
        trader_name: "TraderMax",
        description: "subió al puesto #2",
        asset_symbol: "XAUUSD",
        pnl_pct: 0,
        created_at: "2026-06-04T18:07:00.000Z",
      },
      {
        event_id: "evt_4",
        trader_name: "PipMaster",
        description: "cerró una operación",
        asset_symbol: "XAUUSD",
        pnl_pct: 2.12,
        created_at: "2026-06-04T18:06:00.000Z",
      },
    ],
    mt5_account: {
      login: "9021448",
      server: "Bullfy-Demo",
      status: "CONNECTED",
      balance: 10000,
      equity: 9908.68,
      margin: 214.2,
      free_margin: 9694.48,
      margin_level_pct: 4625.9,
    },
    open_positions: [
      {
        position_id: "pos_1",
        symbol: "EURUSD",
        side: "SELL",
        lots: 0.2,
        entry_price: 1.08742,
        current_price: 1.08918,
        stop_loss: 1.0924,
        take_profit: 1.0821,
        pnl_amount: -35.2,
        pnl_pct: -0.35,
        opened_at: "2026-06-04T17:52:00.000Z",
      },
      {
        position_id: "pos_2",
        symbol: "XAUUSD",
        side: "BUY",
        lots: 0.05,
        entry_price: 2357.1,
        current_price: 2363.8,
        stop_loss: 2349,
        take_profit: 2374,
        pnl_amount: 67.4,
        pnl_pct: 0.67,
        opened_at: "2026-06-04T18:02:00.000Z",
      },
    ],
    trade_ticket: {
      default_symbol: "EURUSD",
      available_symbols: ["EURUSD", "GBPUSD", "XAUUSD", "NAS100"],
      min_lots: 0.01,
      max_lots: 1,
      default_lots: 0.1,
      max_risk_pct: 2,
    },
  },
];

export function createEmptyArenaMockDto(
  tournamentSlug: string,
): ExternalArenaDto {
  return {
    tournament_slug: tournamentSlug,
    spectators_count: 0,
    server_time: new Date().toISOString(),
    leaderboard: [],
    metrics: [
      { label: "Volumen total", value: "$0", trend: "FLAT" },
      { label: "Trades activos", value: "0", trend: "FLAT" },
      { label: "Mejor win rate", value: "0%", trend: "FLAT" },
      { label: "Drawdown medio", value: "0%", trend: "FLAT" },
    ],
    recent_activity: [],
    mt5_account: {
      login: "-",
      server: "Sin conexion",
      status: "DISCONNECTED",
      balance: 0,
      equity: 0,
      margin: 0,
      free_margin: 0,
      margin_level_pct: 0,
    },
    open_positions: [],
    trade_ticket: {
      default_symbol: "EURUSD",
      available_symbols: ["EURUSD", "GBPUSD", "XAUUSD"],
      min_lots: 0.01,
      max_lots: 1,
      default_lots: 0.1,
      max_risk_pct: 2,
    },
  };
}
