import type { ExternalWalletDto } from "./wallet.contracts";

export const walletMockDto: ExternalWalletDto = {
  trader_id: "trader_karlos",
  balances: {
    real_balance: 0,
    demo_balance: 1680,
    bullfy_points: 538,
    pending_rewards: 72.5,
    claimable_rewards: 25,
  },
  payment_methods: [
    {
      method_id: "method_usdt_trc20",
      label: "USDT Wallet",
      network: "TRC20",
      last_four: "8F21",
      status: "ACTIVE",
    },
    {
      method_id: "method_bank_demo",
      label: "Demo Credit",
      network: "Bullfy",
      last_four: "DEMO",
      status: "ACTIVE",
    },
  ],
  movements: [
    {
      movement_id: "mov_001",
      movement_type: "ENTRY_FEE",
      status: "COMPLETED",
      title: "Entrada a devtest3",
      description: "Fee de participacion debitado del balance demo.",
      amount: -120,
      currency: "DEMO",
      created_at: "2026-06-04T16:45:00.000Z",
      tournament_name: "devtest3",
    },
    {
      movement_id: "mov_002",
      movement_type: "POINTS",
      status: "COMPLETED",
      title: "Bonificacion por ranking",
      description: "Bullfy Points acreditados por mantener top 3.",
      amount: 38,
      currency: "BFP",
      created_at: "2026-06-04T18:10:00.000Z",
      tournament_name: "devtest3",
    },
    {
      movement_id: "mov_003",
      movement_type: "REWARD",
      status: "PENDING",
      title: "Premio pendiente",
      description: "Recompensa en validacion del organizador.",
      amount: 72.5,
      currency: "USD",
      created_at: "2026-06-04T19:00:00.000Z",
      tournament_name: "Gold Rush",
    },
    {
      movement_id: "mov_004",
      movement_type: "REWARD",
      status: "COMPLETED",
      title: "Premio reclamado",
      description: "Pago liberado al wallet real.",
      amount: 25,
      currency: "USD",
      created_at: "2026-06-03T21:12:00.000Z",
      tournament_name: "Scalp Night",
    },
    {
      movement_id: "mov_005",
      movement_type: "ADJUSTMENT",
      status: "COMPLETED",
      title: "Recarga demo",
      description: "Asignacion manual para torneos de practica.",
      amount: 500,
      currency: "DEMO",
      created_at: "2026-06-02T14:30:00.000Z",
    },
  ],
};
