import type { Clan, ClanDashboard, ClanWar } from "../types";

export const currentUserId = "trader_karlos";

export const clanMockDtos: Clan[] = [
  {
    id: "clan_bullfy",
    slug: "bullfy-clan",
    name: "Bullfy Clan",
    tag: "BULL",
    description: "Mesa competitiva enfocada en gestion de riesgo y momentum.",
    inviteCode: "BULL-7F4K9",
    isPublic: true,
    isVerified: true,
    rating: 1840,
    rank: 1,
    membersCount: 18,
    warsWon: 12,
    totalWars: 16,
    avgMemberScore: 7.8,
    totalScore: 140.4,
    ownerId: currentUserId,
    createdAt: "2026-05-10T14:00:00.000Z",
    members: [
      {
        id: "trader_karlos",
        name: "Karlos Guzman",
        handle: "karlosg",
        role: "owner",
        joinedAt: "2026-05-10T14:00:00.000Z",
        score: 8.42,
        pnl: 842.6,
        trades: 96,
        winRate: 62,
        verified: true,
      },
      {
        id: "trader_luna",
        name: "Luna Trader",
        handle: "lunafx",
        role: "officer",
        joinedAt: "2026-05-12T18:30:00.000Z",
        score: 5.28,
        pnl: 528.8,
        trades: 88,
        winRate: 57,
        verified: true,
      },
      {
        id: "trader_fx",
        name: "FX Immortal",
        handle: "fximmortal",
        role: "member",
        joinedAt: "2026-05-18T11:20:00.000Z",
        score: 4.73,
        pnl: 473.12,
        trades: 75,
        winRate: 56,
        verified: false,
      },
      {
        id: "trader_nora",
        name: "Nora Gold",
        handle: "noragold",
        role: "member",
        joinedAt: "2026-05-20T10:05:00.000Z",
        score: 3.95,
        pnl: 395.2,
        trades: 64,
        winRate: 54,
        verified: true,
      },
    ],
  },
  {
    id: "clan_alpha",
    slug: "alpha-desk",
    name: "Alpha Desk",
    tag: "ALFA",
    description: "Scalpers agresivos con foco en Londres y New York.",
    inviteCode: "ALFA-2C9M1",
    isPublic: true,
    isVerified: true,
    rating: 1765,
    rank: 2,
    membersCount: 22,
    warsWon: 10,
    totalWars: 15,
    avgMemberScore: 6.9,
    totalScore: 132.8,
    ownerId: "trader_tradermax",
    createdAt: "2026-05-02T09:00:00.000Z",
    members: [
      {
        id: "trader_tradermax",
        name: "TraderMax",
        handle: "tradermax",
        role: "owner",
        joinedAt: "2026-05-02T09:00:00.000Z",
        score: 6.91,
        pnl: 691.24,
        trades: 82,
        winRate: 61,
        verified: true,
      },
      {
        id: "trader_pipmaster",
        name: "PipMaster",
        handle: "pipmaster",
        role: "officer",
        joinedAt: "2026-05-07T13:00:00.000Z",
        score: 3.64,
        pnl: 364.48,
        trades: 69,
        winRate: 55,
        verified: false,
      },
    ],
  },
  {
    id: "clan_moon",
    slug: "moon-clan",
    name: "Moon Clan",
    tag: "MOON",
    description: "Swing traders pacientes, crypto y oro.",
    inviteCode: "MOON-8Q2A4",
    isPublic: true,
    isVerified: false,
    rating: 1610,
    rank: 3,
    membersCount: 15,
    warsWon: 7,
    totalWars: 11,
    avgMemberScore: 5.4,
    totalScore: 96.2,
    ownerId: "trader_queen",
    createdAt: "2026-05-16T19:10:00.000Z",
    members: [
      {
        id: "trader_queen",
        name: "Queen Markets",
        handle: "queenmarkets",
        role: "owner",
        joinedAt: "2026-05-16T19:10:00.000Z",
        score: 2.18,
        pnl: 218.06,
        trades: 64,
        winRate: 51,
        verified: true,
      },
    ],
  },
];

export const clanWarMockDtos: ClanWar[] = [
  {
    id: "war_bull_alpha_live",
    challengerClanId: "clan_alpha",
    defenderClanId: "clan_bullfy",
    status: "in_progress",
    stakeUsd: 250,
    startedAt: "2026-06-05T15:00:00.000Z",
    minParticipants: 3,
    durationMinutes: 1440,
  },
  {
    id: "war_bull_moon_win",
    challengerClanId: "clan_bullfy",
    defenderClanId: "clan_moon",
    winnerClanId: "clan_bullfy",
    status: "finished",
    stakeUsd: 100,
    startedAt: "2026-06-01T15:00:00.000Z",
    endedAt: "2026-06-02T15:00:00.000Z",
    minParticipants: 3,
    durationMinutes: 1440,
  },
  {
    id: "war_moon_alpha_pending",
    challengerClanId: "clan_moon",
    defenderClanId: "clan_alpha",
    status: "pending",
    stakeUsd: 0,
    startedAt: "2026-06-04T21:00:00.000Z",
    minParticipants: 5,
    durationMinutes: 2880,
  },
];

export function getClanDashboardMock(): ClanDashboard {
  return {
    clans: clanMockDtos,
    currentUserClanId: "clan_bullfy",
    currentUserId,
    wars: clanWarMockDtos,
  };
}
