// Generates A/B/C variants of a clip with different hook offsets and AI captions.
// Each variant uses the same source but starts at a slightly different point,
// and has a re-written first-line hook generated by Lovable AI.
const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};
const respond = (p: Record<string, unknown>, s = 200) =>
  new Response(JSON.stringify(p), { status: s, headers: { ...corsHeaders, "Content-Type": "application/json" } });

const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
const serviceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const LOVABLE_KEY = Deno.env.get("LOVABLE_API_KEY")!;
const SHOTSTACK_KEY = Deno.env.get("SHOTSTACK_API_KEY")!;

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: corsHeaders });

  try {
    const { clip_id, num_variants = 3 } = await req.json();
    if (!clip_id) return respond({ ok: false, error: "clip_id required" });

    const authHeader = req.headers.get("authorization") || "";
    const userRes = await fetch(`${supabaseUrl}/auth/v1/user`, {
      headers: { Authorization: authHeader, apikey: Deno.env.get("SUPABASE_ANON_KEY")! },
    });
    if (!userRes.ok) return respond({ ok: false, error: "No autenticado" }, 401);
    const user = await userRes.json();

    const cRes = await fetch(`${supabaseUrl}/rest/v1/video_clips?id=eq.${clip_id}&select=*`, {
      headers: { apikey: serviceKey, Authorization: `Bearer ${serviceKey}` },
    });
    const clip = (await cRes.json())?.[0];
    if (!clip) return respond({ ok: false, error: "Clip no encontrado" });

    // 1. Generate N hook variants via Lovable AI
    const sys = `Eres copywriter viral. Genera ${num_variants} versiones distintas del primer gancho (3-5 segundos iniciales) para un clip vertical de TikTok/Reels.
Cada gancho debe ser MUY diferente entre sí en estilo (pregunta, dato impactante, contradicción).
Devuelve SOLO JSON: {"variants":[{"label":"A","hook":"...","caption":"..."}]}`;

    const aiRes = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: { Authorization: `Bearer ${LOVABLE_KEY}`, "Content-Type": "application/json" },
      body: JSON.stringify({
        model: "google/gemini-2.5-flash",
        messages: [
          { role: "system", content: sys },
          { role: "user", content: `Caption original: """${clip.transcript_segment || clip.title || ""}"""` },
        ],
      }),
    });

    if (!aiRes.ok) return respond({ ok: false, error: `AI error ${aiRes.status}` });
    const aiData = await aiRes.json();
    const text = aiData?.choices?.[0]?.message?.content || "";
    const match = text.match(/\{[\s\S]*\}/);
    if (!match) return respond({ ok: false, error: "AI no devolvió JSON", raw: text });

    let parsed: any;
    try { parsed = JSON.parse(match[0]); } catch { return respond({ ok: false, error: "JSON inválido" }); }
    const variants: any[] = (parsed.variants || []).slice(0, num_variants);

    // 2. For each variant, schedule a Shotstack render with hook offset
    const created: any[] = [];
    const baseDuration = (clip.end_time || 0) - (clip.start_time || 0) || 30;

    for (let i = 0; i < variants.length; i++) {
      const v = variants[i];
      const offset = i * 0.5; // small temporal offset per variant
      const subFont = "Montserrat";

      const renderPayload = {
        timeline: {
          background: "#000000",
          tracks: [
            {
              clips: [{
                asset: { type: "html",
                  html: `<p style="font-family:${subFont},sans-serif;font-size:54px;font-weight:800;color:white;text-align:center;text-shadow:3px 3px 12px rgba(0,0,0,0.95);background:rgba(0,0,0,0.55);padding:18px 28px;border-radius:14px;">${escapeHtml(v.hook || "")}</p>`,
                  width: 960, height: 280,
                },
                start: 0, length: 3, position: "center",
                transition: { in: "fade", out: "fade" },
              }],
            },
            {
              clips: [{
                asset: { type: "video", src: clip.output_url || clip.source_url, trim: offset },
                start: 0, length: baseDuration,
              }],
            },
          ],
        },
        output: { format: "mp4", resolution: "1080", aspectRatio: clip.format === "vertical" ? "9:16" : "16:9" },
      };

      const sRes = await fetch("https://api.shotstack.io/edit/v1/render", {
        method: "POST",
        headers: { "Content-Type": "application/json", "x-api-key": SHOTSTACK_KEY },
        body: JSON.stringify(renderPayload),
      });
      const sData = await sRes.json();
      const renderId = sData.response?.id;

      const insertRes = await fetch(`${supabaseUrl}/rest/v1/clip_variants`, {
        method: "POST",
        headers: { apikey: serviceKey, Authorization: `Bearer ${serviceKey}`, "Content-Type": "application/json", Prefer: "return=representation" },
        body: JSON.stringify({
          parent_clip_id: clip_id,
          variant_label: v.label || String.fromCharCode(65 + i),
          hook_offset_seconds: offset,
          caption: v.caption || v.hook,
          shotstack_render_id: renderId,
          render_status: renderId ? "rendering" : "failed",
          created_by: user.id,
        }),
      });
      const saved = (await insertRes.json())?.[0];
      created.push(saved);
    }

    return respond({ ok: true, variants: created });
  } catch (e) {
    console.error("generate-clip-variants error:", e);
    return respond({ ok: false, error: e instanceof Error ? e.message : String(e) });
  }
});

function escapeHtml(t: string) {
  return t.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}
