import type { ExternalLeaderboardDto } from "./leaderboard.contracts";

export const leaderboardMockDtos: ExternalLeaderboardDto[] = [
  {
    leaderboard_id: "global_live",
    title: "Ranking global",
    scope: "GLOBAL",
    updated_at: "2026-06-04T18:12:00.000Z",
    entries: [
      {
        trader_id: "trader_karlos",
        trader_name: "Karlos Guzman",
        clan_name: "Bullfy Clan",
        rank: 1,
        previous_rank: 1,
        score_pct: 8.42,
        pnl_amount: 842.6,
        balance_amount: 10842.6,
        trades_count: 96,
        win_rate_pct: 62,
      },
      {
        trader_id: "trader_tradermax",
        trader_name: "TraderMax",
        clan_name: "Alpha Clan",
        rank: 2,
        previous_rank: 5,
        score_pct: 6.91,
        pnl_amount: 691.24,
        balance_amount: 10691.24,
        trades_count: 82,
        win_rate_pct: 61,
      },
      {
        trader_id: "trader_luna",
        trader_name: "Luna Trader",
        clan_name: "Moon Clan",
        rank: 3,
        previous_rank: 2,
        score_pct: 5.28,
        pnl_amount: 528.8,
        balance_amount: 10528.8,
        trades_count: 88,
        win_rate_pct: 57,
      },
      {
        trader_id: "trader_fx",
        trader_name: "FX Immortal",
        clan_name: "Legend Clan",
        rank: 4,
        previous_rank: 4,
        score_pct: 4.73,
        pnl_amount: 473.12,
        balance_amount: 10473.12,
        trades_count: 75,
        win_rate_pct: 56,
      },
      {
        trader_id: "trader_pipmaster",
        trader_name: "PipMaster",
        clan_name: "Alpha Clan",
        rank: 5,
        previous_rank: 7,
        score_pct: 3.64,
        pnl_amount: 364.48,
        balance_amount: 10364.48,
        trades_count: 69,
        win_rate_pct: 55,
      },
      {
        trader_id: "trader_queen",
        trader_name: "Queen Markets",
        clan_name: "Gold Clan",
        rank: 6,
        previous_rank: 3,
        score_pct: 2.18,
        pnl_amount: 218.06,
        balance_amount: 10218.06,
        trades_count: 64,
        win_rate_pct: 51,
      },
    ],
  },
  {
    leaderboard_id: "devtest3_live",
    title: "Ranking devtest3",
    scope: "TOURNAMENT",
    updated_at: "2026-06-04T18:12:00.000Z",
    entries: [
      {
        trader_id: "trader_karlos",
        trader_name: "Karlos Guzman",
        clan_name: "Bullfy Clan",
        rank: 1,
        previous_rank: 1,
        score_pct: -0.91,
        pnl_amount: -91.32,
        balance_amount: 9908.68,
        trades_count: 34,
        win_rate_pct: 58,
      },
      {
        trader_id: "trader_tradermax",
        trader_name: "TraderMax",
        clan_name: "Alpha Clan",
        rank: 2,
        previous_rank: 4,
        score_pct: -0.35,
        pnl_amount: -35.12,
        balance_amount: 9964.88,
        trades_count: 28,
        win_rate_pct: 61,
      },
      {
        trader_id: "trader_luna",
        trader_name: "Luna Trader",
        clan_name: "Moon Clan",
        rank: 3,
        previous_rank: 2,
        score_pct: -1.24,
        pnl_amount: -124.31,
        balance_amount: 9875.69,
        trades_count: 41,
        win_rate_pct: 47,
      },
      {
        trader_id: "trader_fx",
        trader_name: "FX Immortal",
        clan_name: "Legend Clan",
        rank: 4,
        previous_rank: 4,
        score_pct: -1.45,
        pnl_amount: -145.32,
        balance_amount: 9854.68,
        trades_count: 36,
        win_rate_pct: 52,
      },
      {
        trader_id: "trader_pipmaster",
        trader_name: "PipMaster",
        clan_name: "Alpha Clan",
        rank: 5,
        previous_rank: 6,
        score_pct: -1.78,
        pnl_amount: -178.04,
        balance_amount: 9821.96,
        trades_count: 29,
        win_rate_pct: 55,
      },
    ],
  },
];
