import type { VersusChallenge, VersusDashboard, VersusTrader } from "../types";

export const currentVersusUserId = "trader_karlos";

export const versusTradersMock: VersusTrader[] = [
  {
    id: "trader_karlos",
    name: "Karlos Guzman",
    username: "karlosg",
    clanTag: "BULL",
    verified: true,
    score: 8.42,
    winRate: 62,
  },
  {
    id: "trader_tradermax",
    name: "TraderMax",
    username: "tradermax",
    clanTag: "ALFA",
    verified: true,
    score: 6.91,
    winRate: 61,
  },
  {
    id: "trader_luna",
    name: "Luna Trader",
    username: "lunafx",
    clanTag: "BULL",
    verified: true,
    score: 5.28,
    winRate: 57,
  },
  {
    id: "trader_pipmaster",
    name: "PipMaster",
    username: "pipmaster",
    clanTag: "ALFA",
    verified: false,
    score: 3.64,
    winRate: 55,
  },
];

export const versusChallengesMock: VersusChallenge[] = [
  {
    id: "versus_live_tradermax",
    status: "live",
    challenger: versusTradersMock[1],
    opponent: versusTradersMock[0],
    tournamentSlug: "devtest3",
    stakeUsd: 50,
    durationMinutes: 180,
    message: "Scalp battle. Londres decide.",
    createdAt: "2026-06-05T12:10:00.000Z",
    acceptedAt: "2026-06-05T12:25:00.000Z",
    startsAt: "2026-06-05T13:00:00.000Z",
    endsAt: "2026-06-05T16:00:00.000Z",
    challengerScore: 3.12,
    opponentScore: 4.36,
  },
  {
    id: "versus_pending_luna",
    status: "pending",
    challenger: versusTradersMock[0],
    opponent: versusTradersMock[2],
    inviteToken: "vs_luna_2026",
    stakeUsd: 0,
    durationMinutes: 1440,
    message: "Reto amistoso de consistencia.",
    createdAt: "2026-06-05T10:30:00.000Z",
    challengerScore: 0,
    opponentScore: 0,
  },
  {
    id: "versus_pending_external",
    status: "pending",
    challenger: versusTradersMock[0],
    opponentEmail: "rival@email.com",
    opponentUsernameHint: "invitado externo",
    inviteToken: "vs_external_2026",
    stakeUsd: 25,
    durationMinutes: 720,
    message: "Invitacion abierta con apuesta baja.",
    createdAt: "2026-06-04T20:15:00.000Z",
    challengerScore: 0,
    opponentScore: 0,
  },
  {
    id: "versus_finished_pip",
    status: "finished",
    challenger: versusTradersMock[3],
    opponent: versusTradersMock[0],
    winnerId: "trader_karlos",
    tournamentSlug: "scalp-night",
    stakeUsd: 100,
    durationMinutes: 240,
    message: "XAUUSD only.",
    createdAt: "2026-06-01T17:00:00.000Z",
    acceptedAt: "2026-06-01T17:20:00.000Z",
    startsAt: "2026-06-01T18:00:00.000Z",
    endsAt: "2026-06-01T22:00:00.000Z",
    challengerScore: 1.44,
    opponentScore: 2.81,
  },
  {
    id: "versus_rejected_queen",
    status: "rejected",
    challenger: versusTradersMock[0],
    opponent: {
      id: "trader_queen",
      name: "Queen Markets",
      username: "queenmarkets",
      clanTag: "MOON",
      verified: true,
      score: 2.18,
      winRate: 51,
    },
    stakeUsd: 0,
    durationMinutes: 1440,
    message: "Swing challenge.",
    createdAt: "2026-05-30T09:00:00.000Z",
    challengerScore: 0,
    opponentScore: 0,
  },
];

export function getVersusDashboardMock(): VersusDashboard {
  return {
    challenges: versusChallengesMock,
    currentUserId: currentVersusUserId,
    suggestedOpponents: versusTradersMock.filter(
      (trader) => trader.id !== currentVersusUserId,
    ),
  };
}
