import type { ExternalProfileDashboardDto } from "./profile.contracts";

export const profileDashboardMockDto: ExternalProfileDashboardDto = {
  trader: {
    trader_id: "trader_karlos",
    display_name: "Karlos Guzman",
    handle: "karlosfx",
    clan_name: "Bullfy Clan",
    avatar_url: "/avatars/karlos.svg",
    country_code: "VE",
    joined_at: "2026-05-12T14:00:00.000Z",
    bio: "Scalper disciplinado. Busco torneos de alta presion y setups limpios en Londres/NY.",
    verified: true,
  },
  wallet: {
    real_balance: 250,
    demo_balance: 1680,
    bullfy_points: 538,
  },
  performance: {
    global_rank: 1,
    current_tournament_rank: 1,
    pnl_pct: -0.91,
    pnl_amount: -91.32,
    win_rate_pct: 58,
    trades_count: 34,
    profit_factor: 1.82,
    max_drawdown_pct: 4.7,
    tournaments_played: 12,
    tournaments_won: 3,
    best_asset: "EURUSD",
  },
  membership: {
    tier: "ELITE",
    status: "ACTIVE",
    renews_at: "2026-07-10T14:00:00.000Z",
    benefits: ["Torneos Elite", "Retiros USDT", "MT5 fondeado", "Clanes verificados"],
  },
  clan: {
    clan_id: "clan_bullfy",
    slug: "bullfy-clan",
    name: "Bullfy Clan",
    tag: "BFY",
    role: "CAPTAIN",
    rank: 4,
    members_count: 18,
  },
  mt5_accounts: [
    {
      account_id: "mt5_demo_1",
      login: "9021448",
      server: "Bullfy-Demo",
      kind: "DEMO",
      status: "CONNECTED",
      equity: 9908.68,
      last_sync_at: "2026-06-04T18:12:00.000Z",
    },
    {
      account_id: "mt5_funded_1",
      login: "7100421",
      server: "Bullfy-Trade",
      kind: "FUNDED",
      status: "PENDING",
      equity: 25000,
      last_sync_at: "2026-06-03T16:30:00.000Z",
    },
  ],
  tournaments: [
    {
      tournament_id: "tournament_devtest3",
      slug: "devtest3",
      tournament_name: "devtest3",
      status: "LIVE",
      rank: 1,
      participants: 20,
      score_pct: -0.91,
      prize_usd: 500,
      started_at: "2026-06-04T16:00:00.000Z",
      ended_at: null,
      result: "ACTIVE",
    },
    {
      tournament_id: "tournament_scalp_night",
      slug: "scalp-night",
      tournament_name: "Scalp Night",
      status: "UPCOMING",
      rank: 0,
      participants: 80,
      score_pct: 0,
      prize_usd: 1200,
      started_at: "2026-06-11T02:00:00.000Z",
      ended_at: null,
      result: "QUALIFIED",
    },
    {
      tournament_id: "tournament_gold_rush",
      slug: "gold-rush",
      tournament_name: "Gold Rush",
      status: "FINISHED",
      rank: 3,
      participants: 50,
      score_pct: 4.18,
      prize_usd: 750,
      started_at: "2026-05-28T18:00:00.000Z",
      ended_at: "2026-05-29T18:00:00.000Z",
      result: "PODIUM",
    },
    {
      tournament_id: "tournament_nasdaq_open",
      slug: "nasdaq-open",
      tournament_name: "Nasdaq Open",
      status: "FINISHED",
      rank: 12,
      participants: 120,
      score_pct: 1.42,
      prize_usd: 1500,
      started_at: "2026-05-19T20:00:00.000Z",
      ended_at: "2026-05-20T20:00:00.000Z",
      result: "QUALIFIED",
    },
    {
      tournament_id: "tournament_fx_sprint",
      slug: "fx-sprint",
      tournament_name: "FX Sprint",
      status: "FINISHED",
      rank: 34,
      participants: 96,
      score_pct: -2.13,
      prize_usd: 650,
      started_at: "2026-05-10T16:00:00.000Z",
      ended_at: "2026-05-11T16:00:00.000Z",
      result: "ELIMINATED",
    },
  ],
  versus: [
    {
      versus_id: "versus_1",
      opponent_name: "Maya Rios",
      opponent_handle: "mayapips",
      status: "FINISHED",
      result: "WIN",
      stake_usd: 50,
      pnl_pct: 2.4,
      score: 1240,
      opponent_score: 1110,
      played_at: "2026-06-04T15:20:00.000Z",
    },
    {
      versus_id: "versus_2",
      opponent_name: "Leo Vela",
      opponent_handle: "velaedge",
      status: "LIVE",
      result: "ACTIVE",
      stake_usd: 25,
      pnl_pct: -0.35,
      score: 540,
      opponent_score: 565,
      played_at: "2026-06-04T18:00:00.000Z",
    },
    {
      versus_id: "versus_3",
      opponent_name: "Rafa Quant",
      opponent_handle: "rafaquant",
      status: "FINISHED",
      result: "LOSS",
      stake_usd: 75,
      pnl_pct: -1.1,
      score: 980,
      opponent_score: 1035,
      played_at: "2026-06-02T21:30:00.000Z",
    },
  ],
  clan_wars: [
    {
      war_id: "war_1",
      opponent_clan: "Alpha Desk",
      opponent_tag: "ALP",
      status: "FINISHED",
      result: "WIN",
      rank_impact: 2,
      clan_score: 8420,
      opponent_score: 8110,
      played_at: "2026-06-01T19:00:00.000Z",
    },
    {
      war_id: "war_2",
      opponent_clan: "London Syndicate",
      opponent_tag: "LSY",
      status: "LIVE",
      result: "ACTIVE",
      rank_impact: 1,
      clan_score: 3120,
      opponent_score: 3280,
      played_at: "2026-06-04T18:00:00.000Z",
    },
    {
      war_id: "war_3",
      opponent_clan: "Quant Wolves",
      opponent_tag: "QW",
      status: "FINISHED",
      result: "LOSS",
      rank_impact: -1,
      clan_score: 7280,
      opponent_score: 7440,
      played_at: "2026-05-22T20:00:00.000Z",
    },
  ],
  recent_trades: [
    {
      trade_id: "trade_1",
      asset_symbol: "EURUSD",
      side: "SELL",
      pnl_amount: -42,
      pnl_pct: -0.42,
      closed_at: "2026-06-04T18:08:00.000Z",
    },
    {
      trade_id: "trade_2",
      asset_symbol: "XAUUSD",
      side: "BUY",
      pnl_amount: 88.7,
      pnl_pct: 0.89,
      closed_at: "2026-06-04T17:55:00.000Z",
    },
    {
      trade_id: "trade_3",
      asset_symbol: "GBPUSD",
      side: "SELL",
      pnl_amount: -19.14,
      pnl_pct: -0.19,
      closed_at: "2026-06-04T17:42:00.000Z",
    },
  ],
};
